language: go

go:
 - 1.1
 - 1.2
 - release
 - tip

install:
 - go get github.com/pilu/traffic
 - go get github.com/go-sql-driver/mysql
 - go get github.com/lib/pq
 - go get github.com/mattn/go-sqlite3
 - go get github.com/naoina/genmai

env:
 - DB=sqlite3
 - DB=mysql
 - DB=postgres

before_script:
 - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS go_traffic_sample_test;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE go_traffic_sample_test;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS go_traffic_sample_test;'; fi"

script:
 - go test -v ./...
