language: go

go:
 - 1.1
 - 1.2
 - release
 - tip

install:
 - go get github.com/pilu/traffic
 - github.com/go-sql-driver/mysql
 - github.com/lib/pq
 - github.com/mattn/go-sqlite3
 - github.com/naoina/genmai

script:
 - go test -v ./...
